### ISSUE TITLE
app open delay

### ISSUE THREAD

**Issue by rintroix** [jooooscha/Olauncher#159] opened 2022-08-23 13:17 UTC
#### Short description
apps don't open while status bar is initially visible (with option to hide status bar, which is on by default). when status bar disappears, apps open correctly. if hide status bar disabled, delay still exists.

#### Steps to reproduce 
1. open launcher
2. immediately try to open app
3. app doesn't open
4. wait for status bar to disappear
5. try open app again
6. it works now

#### Environment information 
- Olauncher CF Version:  1.1.0
- Install Source:  fdroid
- Device:  motorola edge s
- Android:  11
- Other:  battery untersricted

#### expected behavior

apps can be opened immediately when opening launcher

**Comment by jooooscha** [comment] 2022-08-24 06:55
Cannot reproduce on my device. I doubt the status bar option has anything to do with it. 
This sounds more like a android related bug, also I assume it's a pretty minor bug?

**Comment by rintroix** [comment] 2022-08-24 09:10
it is a minor, but rather annoying bug

while i agree that status bar must be unrelated, the timing of its' disappearance and ability to launch apps is super exact. it is also reproducible only while status bar is visible, as in launching launcher while using other app via home gesture. if launcher is open, and home is used, apps open instantly every time, and (coincidentally) status bar is not visible at all.

i think this issue might be describing the same thing https://github.com/tanujnotes/Olauncher/issues/187 because it really feels like sometimes double click is needed

**Comment by rintroix** [comment] 2022-08-24 09:22
upon further testing, double clicking actually opens apps immediately, even before the "status bar disappearance", which is probably some input timeout. it seems to be unrelated to swipe gesture timeout, since swipe apps don't open as well within said timeout. The timeout is about 1.5-2 seconds. So, every time launcher is open, it is necessary to wait for about 2 seconds to even do anything with it

**Comment by jooooscha** [comment] 2022-08-24 13:10
Which rom are do you use?

**Comment by jooooscha** [comment] 2022-08-24 13:13
Which rom are do you use?

I don't understand how to reprpduce you problem.
You say the status bar has to be enabled, but you say it disappears?
What do you mean with open olauncher. Do you mean going back to the home screen from another app, oder do you mean completely closing olauncher and then opening it?

**Comment by rintroix** [comment] 2022-08-25 06:01
it is the default rom that coves with device. it is actually android 12, not 11.

The option `show status bar` is set to `off`. When another app is in foreground, status bar is visible, and when switching to launcher from it, status bar is still shown for about 2 seconds and then fades away. Now that delay between it is still initially shown before fading exactly matches the time apps can't be open with single tap.

The bug exists every time when switching from another app to home screen.

That being said, if it is not reproducible, it must be motorolla's firmware problem, so feel free to close the issue.

**Comment by jooooscha** [comment] 2022-08-25 06:40
Thanks for your clarification.

Can any one reproduce this?

**Comment by Ilithy** [comment] 2022-08-25 06:50
@jooooscha I haven't tested the latest version of OlauncherCF, but on the version installed on my Pixel 6 pro (v1.1.0), I don't have any problem of this kind, the applications launch without delay (and without the need for multiple presses), regardless of the state of the notification bar, sorry, I can't reproduce this bug either

**Comment by alekksander** [comment] 2022-09-01 11:05
there is a delay for gestures as well. i think it's related to android's animation (it has to finish). try disabling to see if it the delay improves or disappears completely.

**Comment by rintroix** [comment] 2022-09-02 07:24
i've disabled all animations in developer tools, so status bar is invisible instantly instead of fading away, but the issues still persists

**Comment by jooooscha** [comment] 2022-09-08 06:41
Do you have the same behavior with the original app?

**Comment by rintroix** [comment] 2022-09-08 08:34
yes, i had the same issue in original

**Comment by jooooscha** [comment] 2022-09-08 14:54
Then, I am afraight this could tale a while to debug.

Did you create an issue in the original?
Do you have any other device you can confirm this on?

**Comment by rintroix** [comment] 2022-09-09 13:25
i don't have any other devices to test at the moment. the link to issue on original repo in second post describes similar problem, so i didn't open a new one.

you can close this issues for now. if i ever get more data than can help, i will reopen it.

**Comment by jooooscha** [comment] 2022-09-11 14:29
Ok, sorry that you have such a bad experience

**Closed by jooooscha** 2022-09-11 14:29 UTC
Labels: bug

**Comment by rintroix** [comment] 2023-02-18 06:46
The issue is definitely in Motorola stock rom. All the launchers except the default one have the same issue. Freezing most of the bundled bloatware solved the issue.

**Comment by alekksander** [comment] 2023-02-18 07:05
I moved to a newer device recently (edge 30). Latest lineageos and cannot invoke any delay at all. My guess it's strictly CPU related.
