### ISSUE TITLE
DT2S issue

### ISSUE THREAD

**Issue by R7010A** [jooooscha/Olauncher#110] opened 2022-07-22 10:47 UTC
#### Steps to reproduce
1. pull down quick settings
2. click anywhere on the desktop to close quick settings
3. use DT2S - no reaction
4.  open settings or an app or .... , close it - DT2S works
5. issue is reproducable

#### Environment information
- Olauncher CF Version: 1.0.0
- Install Source: F-Droid
- Device: realme X2 Pro
- Android: 11
- Other: <>

**Comment by jooooscha** [comment] 2022-07-22 16:53
Cannot confirm bug on my device. How about you @Ilithy

**Comment by Ilithy** [comment] 2022-07-22 17:58
Indeed, I can't reproduce this bug on my devices (Android 12 for both of them, I have no acces to my android 11 device for now)

**Comment by R7010A** [comment] 2022-07-22 18:41
I recorded my screen to show you guys
[`(https://filehorst.de/d/evanEGtn
)`]

**Comment by jooooscha** [comment] 2022-07-24 11:28
This seems to be a bug specific to your setup. This would be very time-consuming to debug and might not even be a bug at our side at all

**Comment by R7010A** [comment] 2022-07-24 14:46
DT2S works after opening  and closing quick settings when all recent apps are closed.
If one ore more apps are opened in the background, DT2S won't work.
Very confusing...

**Comment by Ilithy** [comment] 2022-07-24 15:02
@R7010A: indeed it is strange, and as often (for example the problem of the time format on the #37) the supposed bug (no aggression) is only reported by one user, with several, a Schemes can be drawn more easily.

If other users want to participate, it would be very useful for the developer (who is alone for the maintenance, the corrections and the addition of new functionalities, that represents a consequent investment of time and effort

**Comment by Ilithy** [comment] 2022-07-25 05:40
Hi, I just tested again, this time with version 1.0.1, it works perfectly on my devices with flawless responsiveness <3 (@jooooscha thank you for the excellence of your work). I share with you a video capture (to show the responsiveness and the proper functioning of the option).

[Screen Cpature](https://drive.proton.me/urls/Y95EF4SAT0#O1jvYvMHPDws)

**Comment by jooooscha** [comment] 2022-07-25 06:51
@Ilithy thanks for your testing and all

> DT2S works after opening  and closing quick settings when all recent apps are closed.
> If one ore more apps are opened in the background, DT2S won't work.
> Reproducable
> Very confusing... 

If this is dependent on whether you have apps in the background or not, I am sure this is not a bug in this app, but some weird bug in your specific setup/android version/custom rom/phone.
After all, double tap to sleep havily relies on system libraries, both for detecting the double tap and turning off the phone. There is actually not much done on my side.

Also, this seems to be a very minor bug.
I am closing this for now

**Closed** 2022-07-25 06:51 UTC
Labels: bug

**Comment by R7010A** [comment] 2022-07-25 21:27
No problem.
I checked it on v1.01, but the same.
All fine, can live with this minor bug on my device (maybe settings related.
