### ISSUE TITLE
Custom Font Color

### ISSUE THREAD

**Issue by chezui** [jooooscha/Olauncher#155] opened 2022-08-15 20:57 UTC
**Is your feature request related to a problem? Please describe.** 

The font is hard to view on my phone (AGM M7), would be great if I can make the font bolder, without shading and change the color to something high contrast like white.

**Describe the solution you'd like** 

In addition to font size have option to set font bolder, without shading and change the color to something high contrast like white.

**Describe alternatives you've considered** 

- A clear and concise description of any alternative solutions or features you've considered.

**Additional context** 

- Add any other context or screenshots about the feature request here.

**Comment by jooooscha** [comment] 2022-08-16 06:05
Duplicate of #49

**Closed** 2022-08-16 06:05 UTC
Labels: feature
